### ISSUE TITLE
jump to specific index of page failed

### ISSUE THREAD

**Issue by sharedcare** [yysskk/SwipeMenuViewController#100]
I wrote following method in my code. However jump function does not work in this situation, it only jumps to the second page. 
```swift
func swipeMenuView(_ swipeMenuView: SwipeMenuView, viewDidSetupAt currentIndex: Int) {
        swipeMenuView.jump(to: selectedPage, animated: true)
    }
```

**Comment by curiousurick** [comment]
I'm having the same issue.

**Comment by mpg-yamato-mogi** [comment]
I'm having the same issue also.

**Comment by jameszyao** [comment]
the same issue

**Comment by ericosg** [comment]
Here's how I fixed it, hopefully helps you too:

Change `public func jump`:
in
`SwipeMenuView.swift`:

```     /// Jump to the selected page.
    public func jump(to index: Int, animated: Bool) {
         guard let tabView = tabView, let contentScrollView = contentScrollView else { return }
         if currentIndex != index {
             delegate?.swipeMenuView(self, willChangeIndexFrom: currentIndex, to: index)
+            isJumping = true // This was added to fix the jump() as it wasn't working
+        } else {
+            // This was added to fix the jump() as it wasn't working
+            isJumping = false
         }
         jumpingToIndex = index
         tabView.jump(to: index)
         contentScrollView.jump(to: index, animated: animated)
     }

**Comment by ericosg** [comment]
> Here's how I fixed it, hopefully helps you too:
> 
> Change `public func jump`:
> in
> `SwipeMenuView.swift`:
> 
> ```
>     public func jump(to index: Int, animated: Bool) {
>          guard let tabView = tabView, let contentScrollView = contentScrollView else { return }
>          if currentIndex != index {
>              delegate?.swipeMenuView(self, willChangeIndexFrom: currentIndex, to: index)
> +            isJumping = true // This was added to fix the jump() as it wasn't working
> +        } else {
> +            // This was added to fix the jump() as it wasn't working
> +            isJumping = false
>          }
>          jumpingToIndex = index
>          tabView.jump(to: index)
>          contentScrollView.jump(to: index, animated: animated)
>      }
> ```

This shouldn't be considered a fix, nor does it seem to be fixed otherwise, but as a solution it might help. It's causing more problems for me so I won't recommend the above.

**Comment by bellebethcooper** [comment]
I made a fork and a couple of very small changes fixed this issue for me. [Here's the commit](https://github.com/bellebethcooper/SwipeMenuViewController/commit/4e8bff41fbd5e4cf0d54b7993211b464cc281cf9) that got jumping to a specific index working for me.

**Comment by sharedcare** [comment]
@bellebethcooper 's method works for me.
