### ISSUE TITLE
itemViews index out of range in SwipeMenuViewController viewDidLoad callback

### ISSUE THREAD

**Issue by DesmondDAI** [yysskk/SwipeMenuViewController#14]
I am using:
- Version: 1.1.5
- `pod install`
- Xcode: 8.2.1
- Swift: 3.0.2

Following the example and usage in README, I subclass `SwipeMenuViewController` and implement necessary data source methods. But the exception is thrown when `SwipeMenuViewController` calling `view.addSubview(swipeMenuView)` inside `viewDidLoad`.

In the bottom, `TabView` calls `animateUnderlineView`, when accessing `self.currentItem`, the getter method trying to return `itemViews[currentIndex]`, which raises **index out of range exception** since `itemViews` is empty. Note that at this time, the data source methods have not been called, and `swipeMenuView.dataSource` is setup before `view.addSubview(swipeMenuView)`.

I can run the example project (tag 1.1.5 commit) successfully, and follow the same setup as it did in my project. But the problem still happens.

If more information is needed, please tell me. Thanks!

**Comment by yysskk** [comment]
Hi, @DesmondDAI !!
The minimum implementation with SwipeMenuViewController is as follows.

```
import UIKit
import SwipeMenuViewController

class ViewController: SwipeMenuViewController {

    var datas: [String] = ["Bulbasaur","Caterpie", "Golem", "Jynx", "Marshtomp", "Salamence", "Riolu", "Araquanid"]

    var options = SwipeMenuViewOptions()

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillApear(animated)
        swipeMenuView.reloadData(options: options)
    }

    // MARK - SwipeMenuViewDataSource

    override func numberOfPages(in swipeMenuView: SwipeMenuView) -> Int {
        return dataCount
    }

    override func swipeMenuView(_ swipeMenuView: SwipeMenuView, titleForPageAt index: Int) -> String {
        return datas[index]
    }

    override func swipeMenuView(_ swipeMenuView: SwipeMenuView, viewControllerForPageAt index: Int) -> UIViewController {
        let vc = ContentViewController()
        return vc
    }
}
```

In your information, I did not know the cause, so I will review it if you give the code to Github :-)

**Comment by DesmondDAI** [comment]
Hi, @yysskk 
just Tried with the following implementation, same error still comes out.
```swift
class HistoryContainerViewController: SwipeMenuViewController {

    let datas: [String] = ["Bulbasaur","Caterpie", "Golem", "Jynx", "Marshtomp", "Salamence", "Riolu", "Araquanid"]
    let options = SwipeMenuViewOptions()
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        swipeMenuView.reloadData(options: options)
    }
    
}


extension HistoryContainerViewController {
    
    override func numberOfPages(in swipeMenuView: SwipeMenuView) -> Int {
        return datas.count
    }
    
    override func swipeMenuView(_ swipeMenuView: SwipeMenuView, titleForPageAt index: Int) -> String {
        return datas[index]
    }
    
    override func swipeMenuView(_ swipeMenuView: SwipeMenuView, viewControllerForPageAt index: Int) -> UIViewController {
        let vc = UIViewController()
        vc.view.backgroundColor = .yellow
        return vc
    }
}
```

The simple stack trace is:
```swift
```

**Comment by yysskk** [comment]
@DesmondDAI , I created a demonstration project, so please refer to it. 
https://github.com/yysskk/SwipeMenuViewExample

Also, I do not know your situation, so if you upload the repository to Github you can give me more advice.
