### ISSUE TITLE
important problem

### ISSUE THREAD

**Issue by lizizi** [yysskk/SwipeMenuViewController#15]
when i use "swipeMenuView.jump(to: index)",
the delegate's toIndex is not right

![default](https://user-images.githubusercontent.com/19514497/32882589-e01426f0-caef-11e7-9a9b-c760f94e9975.png)

code:
 public func jump(to index: Int) {

        if let tabView = tabView, let contentScrollView = contentScrollView {
            tabView.jump(to: index)
            currentIndex = index-----------> add this
            contentScrollView.jump(to: index, animated: false)
        }
    }
-----------------------------
when i do this ,the index order is right

**Comment by yysskk** [comment]
Hi, @lizizi 
Thank you for your reporting. 
It resolved this problem for https://github.com/yysskk/SwipeMenuViewController/pull/16 🎉

**Comment by yysskk** [comment]
<img width="570" alt="2017-11-17 19 43 11" src="https://user-images.githubusercontent.com/7744927/32943506-b682dcc4-cbcf-11e7-9a89-85bafa33773e.png">

**Comment by Navoda-BrightSparks** [comment]
hello I want to scroll the child view controllers vertically .but because of horizontal page scrolling it doesn't working how to fix it
