### ISSUE TITLE
Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by m-irfan** [yysskk/SwipeMenuViewController#17]
I am getting this error in UIColorExtension.swift file, please see the screenshot attached
I have Xcode Version 9.1 (9B55) and compiler is set to swift 4

<img width="677" alt="screen shot 2017-11-24 at 3 38 26 pm" src="https://user-images.githubusercontent.com/16814075/33206931-b53ead3a-d12d-11e7-90e3-5be7fce32eea.png">

**Comment by yysskk** [comment]
Hi, @m-irfan 
This problem already resolved [ver. 2.0.0](https://github.com/yysskk/SwipeMenuViewController/releases/tag/2.0.0) or later.
