### ISSUE TITLE
No status bar in iOS 11.1

### ISSUE THREAD

**Issue by varun-naharia** [yysskk/SwipeMenuViewController#18]
There is no status bar(network signal, battery etc.) in iOS 11.1 please fix this

![screen shot 2017-12-04 at 2 33 56 pm](https://user-images.githubusercontent.com/10987732/33544286-3c1b9dac-d900-11e7-85c9-d46c62035fd2.png)

**Comment by yysskk** [comment]
@varun-naharia , thanks reporting.
Fix this problem in [version 2.0.5](https://github.com/yysskk/SwipeMenuViewController/releases/tag/2.0.5)
