### ISSUE TITLE
Text colour changing back to black on swipe.

### ISSUE THREAD

**Issue by varun-naharia** [yysskk/SwipeMenuViewController#19]
I set text colour to lightGray and it's working fine with tab changing through tap on tab name but it's changing colour to black when I change tab through swipe.

![image](http://g.recordit.co/eCb0QiraV1.gif)

**Comment by yysskk** [comment]
Hi, @varun-naharia. 
This is an existing bug in `needsConvertTextColorRatio` option.There are two solutions to this.

1. Turn off the `needsConvertTextColorRatio` option
```
options.tabView.needsConvertTextColorRatio = false
```

2. You specify the color of textColor and selectedTextColor in this way(ex. `UIColor(red: CGFloat, green: CGFloat, blue: CGFloat, alpha: CGFloat)`). Not specify UIColor.lightGray, UIColor.red

**Comment by varun-naharia** [comment]
Hi @yysskk .

Thanks for the reply and point out where is the bug in the code, I created another issue where phone status bar is not visible please take a look at that issue also.

**Comment by yysskk** [comment]
@varun-naharia Fix that the requireConvertTextColorRatio condition is not valid
 in this case by https://github.com/yysskk/SwipeMenuViewController/tree/2.0.4

> Thanks for the reply and point out where is the bug in the code, I created another issue where phone status bar is not visible please take a look at that issue also.

Thank you for reporting. I'll see it later :-)
