### ISSUE TITLE
Not rendering all cells inside collectionview

### ISSUE THREAD

**Issue by jaksatomovic** [yysskk/SwipeMenuViewController#21]
if i add collection view programmatically inside contentviewcontroller and i want to have 10 cells inside it is not showing them all

**Comment by yysskk** [comment]
Hi, @jaksatomovic.
I'll review it if you give Github a code :-)

**Comment by trancongthanh1992** [comment]
@jaksatomovic I have same problem. Could u tell me how i can resolve it ?
