### ISSUE TITLE
ViewController's viewWillAppear function will not be invoke when click tab

### ISSUE THREAD

**Issue by yaoliangjun** [yysskk/SwipeMenuViewController#22]
When I click the tab, viewController's viewWillAppear function will not be invoke? any suggestions?

**Comment by yysskk** [comment]
Hi, @yaoliangjun .
Since it is generating the ViewController with the initial loading, `func viewWillAppear()` is supposed not to be called.
Set delegate and call it with `func swipeMenuView(_ swipeMenuView: SwipeMenuView, willChangeIndexFrom fromIndex: Int, to toIndex: Int)
`

**Comment by yaoliangjun** [comment]
thanks!

**Comment by Arshad-iOSDeveloper** [comment]
@yysskk Can you please share the code ?
Thanks
