### ISSUE TITLE
Tab title is transparent until swap to change tab.

### ISSUE THREAD

**Issue by varun-naharia** [yysskk/SwipeMenuViewController#27]
I am using below code 

```
override func viewDidLoad() {
        super.viewDidLoad()
        options.tabView.style = .flexible
        options.tabView.margin                          = 8.0
        options.tabView.underlineView.backgroundColor   = UIColor.white
        options.tabView.backgroundColor                 = UIColor(red: 0.18, green: 0.18, blue: 0.18, alpha: 1.00)
        options.tabView.underlineView.height            = 3.0
        options.tabView.itemView.textColor              = UIColor(red: 0.60, green: 0.60, blue: 0.60, alpha: 1.00)
        options.tabView.itemView.selectedTextColor      = UIColor(red: 1.00, green: 1.00, blue: 1.00, alpha: 1.00)
        options.tabView.itemView.margin                 = 10.0
        options.contentScrollView.backgroundColor       = UIColor.lightGray
        options.tabView.isSafeAreaEnabled = true
        options.tabView.height = 60
        self.reload()
        // Do any additional setup after loading the view.
    }
```

It was working fine when I used `options.tabView.style = .segmented` but after changing it to .flexible now at first launch tab title is not showing but when I try to swap tab it becomes visible as you can see in screeshot

![egxkbjga5g](https://user-images.githubusercontent.com/10987732/37077712-2c708174-2202-11e8-984b-5c4269aba9af.gif)

What's wrong I am doing here ?

**Comment by antscript** [comment]
Do it in main thread:
`
override func viewDidLoad() {
        super.viewDidLoad()
        DispatchQueue.main.async {[weak self] in
                self?.options.tabView.style = .flexible
                self?.options.tabView.margin                          = 8.0
                self?.options.tabView.underlineView.backgroundColor   = UIColor.white
                self?.options.tabView.backgroundColor                 = UIColor(red: 0.18, green: 0.18, blue: 0.18, alpha: 1.00)
                self?.options.tabView.underlineView.height            = 3.0
                self?.options.tabView.itemView.textColor              = UIColor(red: 0.60, green: 0.60, blue: 0.60, alpha: 1.00)
                self?.options.tabView.itemView.selectedTextColor      = UIColor(red: 1.00, green: 1.00, blue: 1.00, alpha: 1.00)
                self?.options.tabView.itemView.margin                 = 10.0
                self?.options.contentScrollView.backgroundColor       = UIColor.lightGray
                self?.options.tabView.isSafeAreaEnabled = true
                self?.options.tabView.height = 60
                self?.reload()
        }
        // Do any additional setup after loading the view.
    }
`

**Comment by yysskk** [comment]
It is probably a problem of autolayout constraints in your project
