### ISSUE TITLE
Unable to find a specification for `SwipeMenuViewController`

### ISSUE THREAD

**Issue by shen5214444887** [yysskk/SwipeMenuViewController#3]
platform :ios, '8.0'

target 'testSwift' do
  use_frameworks!

pod 'SwipeMenuViewController'

end

-------------
pod install  
Unable to find a specification for `SwipeMenuViewController`

**Comment by rai21** [comment]
Same here, Unable to find specification for SwipeMenuViewController (using Objective-C)

**Comment by yysskk** [comment]
Please, try this.
``` 
$ pod repo remove master
$ pod setup
$ pod install
```

with reference to https://stackoverflow.com/questions/25913733/unable-to-find-a-specification-in-cocoapods

**Comment by rai21** [comment]
It worked. Thank you
