### ISSUE TITLE
Button On Child View Does not perform Action

### ISSUE THREAD

**Issue by HarooniAtInfocaliper** [yysskk/SwipeMenuViewController#34]
I am using child views to swipe through "Swipe Menu View Controller", In One of two child views i have created a button and create an IBAction Function related to it. when i press the button, it highlighted but not call IB Action Function. Please Help, Below is the code and relevant image of ChildViewController for referance.

import UIKit

class ChildViewController: UIViewController {
    var trip:String? = nil
    override func viewDidLoad() {
        super.viewDidLoad()  
    }
    @IBAction func test() {
        print("Test")
    }  
}

![github](https://user-images.githubusercontent.com/38242214/38543918-6086e55c-3cbf-11e8-8d91-413d078554b4.png)

**Comment by mojtaba-almoussawi** [comment]
set the delegate and override method  swipeMenuView(_ swipeMenuView: SwipeMenuView, viewControllerForPageAt index: Int) , then before returning the viewController , call addChildViewController method.

`  override func swipeMenuView(_ swipeMenuView: SwipeMenuView, viewControllerForPageAt index: Int) -> UIViewController {
        let vc = ChildViewController()
        addChildViewController(vc)
        return vc
    }`

**Comment by yysskk** [comment]
👍
