### ISSUE TITLE
How can I set the underlineView's width equals titleLabel.

### ISSUE THREAD

**Issue by hengchengfei** [yysskk/SwipeMenuViewController#42]
I want to set the underlineView's width.

underlineView's width = itemview.titleLabel.width

![1](https://user-images.githubusercontent.com/3182964/40474192-f837db26-5f70-11e8-85c6-1958a975b9a2.jpeg)

**Comment by yysskk** [comment]
Hi, @hengchengfei. Please set this options

```
options.tabView.underlineView.margin = 0
```

**Comment by yysskk** [comment]
@hengchengfei Like this ?

![simulator screen shot - iphone 8 plus - 2018-05-31 at 15 47 50](https://user-images.githubusercontent.com/7744927/40766339-1fa60434-64ea-11e8-81c9-3d81b07e7e31.png)

**Comment by hengchengfei** [comment]
like this.
![1](https://user-images.githubusercontent.com/3182964/40768142-088ff276-64e7-11e8-84dc-85fdb9eaf050.jpeg)

**Comment by yysskk** [comment]
We do not publish such an API in this project, so it seems that it can not be realized.

**Comment by clubnika** [comment]
options.tabView.additionView.padding =  UIEdgeInsets(horizontal: 25.0, vertical: 0)
 play with values
