### ISSUE TITLE
How to set defaultIndex?

### ISSUE THREAD

**Issue by hengchengfei** [yysskk/SwipeMenuViewController#46]
When I reload the swipeMenuView,I want to remember the lastly selected index.

Such as fllows:
```swift
options.defaultIndex = 1
swipeMenuView.reloadData(options: options)
```

Thank you!

**Comment by mojtaba-almoussawi** [comment]
Before reloading the swipMenuView, you can get the current index and assign it to a variable, as follow 
someVar = swipeMenuView.currentIndex

**Comment by yysskk** [comment]
👍
