### ISSUE TITLE
Set font to the menu labels

### ISSUE THREAD

**Issue by ggdiez** [yysskk/SwipeMenuViewController#5]
Hello and thanks for the effort to create this control. 

How I can access to the items of the Swipe Menu to set for example:
- The font
- The accessibility labels

Thank you,

**Comment by yysskk** [comment]
Hi, @ggdiez .
I added font options for item view in [version 1.1.3](https://github.com/yysskk/SwipeMenuViewController/tree/1.1.3) .

Try it, please.

**Comment by ggdiez** [comment]
Great job ;)
