### ISSUE TITLE
Addiction view padding left

### ISSUE THREAD

**Issue by YuraChudnick** [yysskk/SwipeMenuViewController#52]
Hello! 
When I set this option:
options.tabView.additionView.padding          = .init(top: 0, left: 16, bottom: 0, right: 16)
padding left on start did not apply.
Can you help me to fix this?

**Comment by DimaZava** [comment]
Encountering the same issue

**Comment by DimaZava** [comment]
Perhaps found solution for this. 
`fileprivate func resetAdditionViewPosition(index: Int)`
function in TabView.swift file, line 398
which is originally looks like
`additionView.frame.origin.x = adjustCellWidth * CGFloat(index) - options.additionView.padding.left`
but should be
`additionView.frame.origin.x = adjustCellWidth * CGFloat(index) + options.additionView.padding.left`

**Comment by YuraChudnick** [comment]
Thank You! It works.
