### ISSUE TITLE
Issue when clicking the view buttons too fast

### ISSUE THREAD

**Issue by mbasnillo** [yysskk/SwipeMenuViewController#57]
Hi, when you tap two of the navigation items too fast, the view controller will not change but the addition (underline) will still move to the next last clicked one.

Example: 
1) Starting at Bulbasaur, I tapped Caterpie then quickly tapped Bulbasaur again
2) The underline moved from Caterpie then to Bulbasaur immediately, but the view controller stayed at Caterpie.

Was reproduced on an iPhone 8 Plus (11.3) with the latest version, and the issue also happens in other iPhones as well.

![image](https://user-images.githubusercontent.com/13742614/42358940-c084ed46-8111-11e8-80cd-c5fc65861c4d.png)

**Comment by Terens777** [comment]
Was this problem solved?

**Comment by Terens777** [comment]
@mbasnillo 
How did you solve the problem? or is there a better way to not use this framework?

**Comment by Terens777** [comment]
The creator probably abandoned the framework, as I understand it, I will not recommend it and use it, thanks

**Comment by Terens777** [comment]
@yysskk  You are alive?

**Comment by sandro93** [comment]
same problem for me, any ideas?

**Comment by Terens777** [comment]
@sandro93  The only idea is not to use this library, unfortunately
(
