### ISSUE TITLE
there are some problems

### ISSUE THREAD

**Issue by lizizi** [yysskk/SwipeMenuViewController#6]
public var currentIndex 
this is not public 
--------------
when i use   swipeMenuView jump to ()
they can't jump to right index 
-------------------

**Comment by Netwolf** [comment]
`  public func jump(to index: Int) {

        if let tabView = tabView, let contentScrollView = contentScrollView {
            tabView.jump(to: index)
            contentScrollView.jump(to: index, animated: true)
        }
    }`

**Comment by yysskk** [comment]
> public var currentIndex
this is not public

> when i use swipeMenuView jump to ()
they can't jump to right index

It resolved this problem for https://github.com/yysskk/SwipeMenuViewController/commit/cc1c6c8e286f4741d83cfb2eeaee6757c457d6a6 , https://github.com/yysskk/SwipeMenuViewController/pull/8
Thank you for reporting 🙏
