### ISSUE TITLE
Swift 4.2 / Xcode 10.0 version Error

### ISSUE THREAD

**Issue by jasudev** [yysskk/SwipeMenuViewController#62]
Describe the bug
 
Build system information
 
Showing Recent Messages
:-1: Multiple commands produce '/Users/jasu/Library/Developer/Xcode/DerivedData/Folder-fvgwuawkkumkbnbwxdxvjausocav/Build/Products/Debug-iphonesimulator/SwipeMenuViewController/SwipeMenuViewController.framework/Info.plist':
Target 'SwipeMenuViewController' (project 'Pods') has copy command from '/Users/jasu/Folder/Folder/Pods/SwipeMenuViewController/Sources/Supporting files/Info.plist' to '/Users/jasu/Library/Developer/Xcode/DerivedData/Folder-fvgwuawkkumkbnbwxdxvjausocav/Build/Products/Debug-iphonesimulator/SwipeMenuViewController/SwipeMenuViewController.framework/Info.plist'
Target 'SwipeMenuViewController' (project 'Pods') has process command with output '/Users/jasu/Library/Developer/Xcode/DerivedData/Folder-fvgwuawkkumkbnbwxdxvjausocav/Build/Products/Debug-iphonesimulator/SwipeMenuViewController/SwipeMenuViewController.framework/Info.plist'
 
I get an error when building in Swift 4.2 / Xcode 10.0. Can it be checked quickly?
thanks

**Comment by jasudev** [comment]
The problem was that the Info.plist file was duplicated in the Pods project. Removing the Info.plist file from the Compile Source list in the Pods project SwipeMenuViewController project will resolve the problem.

**Comment by jasudev** [comment]
> I have the same issue, can you tell me where should I remove the info.plist file? I'm new to swift so I appreciate your help in advance, I also get this error when I wanna import the library:
> "Could not build Objective-C module 'SwipeMenuViewController'"

Pods -> SwipeMenuViewController target -> Build Phases -> Compile Sources
Please delete the Info.pllist file included in the above path and build it.

**Comment by R-Ashh** [comment]
thanks for the help, I've been on it about 30 hours and couldn't fix it, one other thing, have you made **[this](https://github.com/yysskk/Assets/blob/master/SwipeMenuViewController/demo_segmented.gif)** example with this lib? I'm new to Swift, I used to do Android and still do, in android when you implement dependencies you can saw them in XML file where you create the views, do I have to code this module out to use it? as an object in Swift? or is there any way I can do this with View in one of StoryBoards?

**Comment by vishveshdiyora** [comment]
> > I have the same issue, can you tell me where should I remove the info.plist file? I'm new to swift so I appreciate your help in advance, I also get this error when I wanna import the library:
> > "Could not build Objective-C module 'SwipeMenuViewController'"
> 
> Pods -> SwipeMenuViewController target -> Build Phases -> Compile Sources
> Please delete the Info.pllist file included in the above path and build it.

where is this????? path i did't find
