### ISSUE TITLE
Could not build Objective-C module 'SwipeMenuViewController'

### ISSUE THREAD

**Issue by R-Ashh** [yysskk/SwipeMenuViewController#63]
Hi, Thank you for your great Library, there's some issue with it tho, when I'm adding it into the Podfile and wanna import it to my ViewController I get this weird error "Could not build Objective-C module 'SwipeMenuViewController'" and I don't know how to fix it, does anyone have this problem? or does anyone know how I can use it in Xcode 10 swift 4?

**Comment by yysskk** [comment]
Try it to remove caches

```
$ rm -rf ~/Library/Developer/Xcode/DerivedData
```
