### ISSUE TITLE
Adding a collection view to my pages and the cells are goingoff page

### ISSUE THREAD

**Issue by GurdevSingh94** [yysskk/SwipeMenuViewController#66]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iPhone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS11.1]
 - Version [e.g. 2.1.0]

**Additional context**

**Comment by wasimshigri** [comment]
i am facing same. did you got any help?

**Comment by yysskk** [comment]
Needs `addChild(someViewController)` and when it present viewController

SeeAlso: https://github.com/yysskk/SwipeMenuViewController/issues/26
