### ISSUE TITLE
Cannot install v3.0.0 via cocoapods

### ISSUE THREAD

**Issue by shingohry** [yysskk/SwipeMenuViewController#70]
I installed SwipeMenuViewController v3.0.0 via cocoapods to my project. 

But SwipeMenuViewController imported into my project was not v3.0.0. (It was not support Swift 4.2)

Is the tag "3.0.0" pointing to the wrong commit?
https://github.com/yysskk/SwipeMenuViewController/releases/tag/3.0.0

**Comment by yysskk** [comment]
@shingohry Thanks, report. I fixed 3.0.0 version tag 🙏
