### ISSUE TITLE
How to Jump to second tabview at initially without taping the send tab

### ISSUE THREAD

**Issue by hilajqinnovation** [yysskk/SwipeMenuViewController#96]
**Describe the bug**
I want to show the second tab as selected one when open the screen without taping the second tab. So I'm calling the jump method of swipeMenuViewController like this
self.swipeMenuView.jump(to: 1, animated: true). Then I'm getting callback in the following delegate method.
func swipeMenuView(_ swipeMenuView: SwipeMenuView, didChangeIndexFrom fromIndex: Int, to toIndex: Int) {
}

But the problem is, in this method, I'm getting toIndex as 0, and always. showing the selected tab as first one. How can I show the selected tab as second tab.
**To Reproduce**

**Expected behavior**

**Screenshots**

**iPhone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS11.1]
 - Version [e.g. 2.1.0]

**Additional context**

**Comment by dimpy-iroid** [comment]
How did you find the solution for this?
